[package]
name = "ray_ray_a2"
version = "0.1.0"
edition = "2021"

[dependencies]
pretty_env_logger = "*"
log = "0.4.21"
pretty_assertions = "1.4.0"
anyhow = "1.0.94"

[[bin]]
name = "projectile_sim"
path = "src/sims/projectile.rs"

[lib]
path = "src/lib.rs"